import { Settings, ShieldCheck } from "lucide-react";
import type { AdminSession } from "@/lib/auth/admin-session";
import { AdminPage, PageIntro } from "@/components/admin-page";
import { DetailTile } from "@/components/admin-primitives";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";

export function SettingsPage({ session }: { session: AdminSession }) {
  const config = { projectId: process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID ?? "gemfort", authDomain: process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN ?? "gemfort.firebaseapp.com", storageBucket: process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET ?? "gemfort.firebasestorage.app" };
  return <AdminPage><PageIntro eyebrow="Workspace" title="Admin settings" description="Review the connected Firebase project and the controls protecting this console." /><div className="grid gap-4 lg:grid-cols-2"><Card><CardHeader><div className="flex size-10 items-center justify-center rounded-2xl bg-primary/10 text-primary"><ShieldCheck aria-hidden="true" /></div><CardTitle>Firebase connection</CardTitle><CardDescription>This console points at the same project used by the GemFort mobile app.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><DetailTile label="Project ID" value={config.projectId} /><DetailTile label="Auth domain" value={config.authDomain} /><DetailTile label="Storage bucket" value={config.storageBucket} /><DetailTile label="Firestore region" value="asia-south1 · Standard edition" /></CardContent></Card><Card><CardHeader><div className="flex size-10 items-center justify-center rounded-2xl bg-accent text-accent-foreground"><Settings aria-hidden="true" /></div><CardTitle>Current session</CardTitle><CardDescription>Only this signed-in user can initiate the actions below.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3"><DetailTile label="Email" value={session.email ?? "—"} /><DetailTile label="Email verified" value={session.emailVerified ? "Yes" : "No"} /><DetailTile label="Provider" value="Firebase Email/Password" /><Alert><ShieldCheck aria-hidden="true" /><AlertTitle>Authorization boundary</AlertTitle><AlertDescription>The browser receives only public Firebase web config. Server Actions re-check the HttpOnly admin session before every mutation.</AlertDescription></Alert></CardContent></Card></div></AdminPage>;
}
